### ISSUE TITLE
show limited posts

### ISSUE THREAD

**Issue by robertnicjoo** [mgmartel/WP-Tiles#25]
Hi, thanks for this plugin
I've an issue; How if I only want to show my last 8 posts?

for example I want use it in my home page and I no need load more button which I can turn it off right now but how to show only the numbers of my latest posts?

Thanks.

**Comment by shropshireitc** [comment]
Did you ever get a response to this?

**Comment by thebrownfox** [comment]
I'm trying to do the same right now.
@mgmartel Could you help us? Would be grateful :)

**Comment by mgmartel** [comment]
Hi all. You can hide the pagination by adding `pagination=none` to the shortcode. You can limit the amount of posts shown with `posts_per_page`.

Putting all together:

`[wp-tiles pagination=none posts_per_page=8]`

With all your other parameters added of course!
